// This configuration was generated by `exe/eslint_autogen`
// on 2026-02-16 00:59:23 UTC.
// The point is for the user to remove these configuration records
// one by one as the offenses are removed from the code base.

import type {Linter} from "eslint";

const config: Linter.Config[] = [
];

export default config;
