// This configuration was generated by `exe/eslint_autogen`
// on 2025-12-16 22:19:02 UTC.
// The point is for the user to remove these configuration records
// one by one as the offenses are removed from the code base.

export default [
];
