inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  DefaultFormatter: fuubar
  DisplayCopNames: true
  EnabledByDefault: true

################################################################################
#
# Rules that depart from rubocop defaults
#
################################################################################

# https://github.com/rubocop-hq/rubocop/issues/7841
Style/TrailingCommaInBlockArgs: { Enabled: false }
Layout/LineLength:
  Max: 80
  AutoCorrect: true
  Exclude: ['config/**/*']
Layout/TrailingEmptyLines: { Enabled: false }
Metrics/BlockLength:
  AllowedMethods:
    - describe
  Exclude:
    - Guardfile
    - db/schema.rb
    - config/environments/development.rb
Rails/FilePath: { EnforcedStyle: slashes }
Metrics/MethodLength: { Exclude: [db/migrate/**/*.rb] }
RSpec/MultipleExpectations:
  Exclude:
    - spec/system/**/*.rb
RSpec/MessageExpectation: { EnforcedStyle: expect }
Style/ArrayFirstLast: { Exclude: [Guardfile] }
Style/CommentedKeyword: { Enabled: false }
Style/MethodCallWithArgsParentheses:
  AllowedMethods:
    - attr_accessor
    - attr_reader
    - attr_writer
    - belongs_to
    - cattr_accessor
    - context
    - default
    - delegate
    - describe
    - exec
    - exit
    - fit
    - gem
    - has_many
    - helper_method
    - include
    - it
    - layout
    - load
    - normalizes
    - not_to
    - p
    - puts
    - raise
    - require
    - require_relative
    - ruby
    - source
    - store_accessor
    - to
    - validates
    - warn
  IgnoreMacros: false
  Exclude:
    - bin/**/*
    - 'config.ru'
    - 'config/boot.rb'
    - 'config/puma.rb'
    - 'config/routes.rb'
    - db/**/*.rb
    - Guardfile
    - Gemfile
Style/MixinUsage: { Exclude: ['bin/**/*'] }
Style/NumericLiterals: { Exclude: [db/schema.rb] }
Style/StringLiterals: { EnforcedStyle: double_quotes }
Style/StringLiteralsInInterpolation: { EnforcedStyle: double_quotes }
Style/SymbolArray: { EnforcedStyle: brackets }
Style/TrailingCommaInArguments: { EnforcedStyleForMultiline: comma }
Style/TrailingCommaInArrayLiteral: { EnforcedStyleForMultiline: comma }
Style/TrailingCommaInHashLiteral: { EnforcedStyleForMultiline: comma }
Style/WordArray: { EnforcedStyle: brackets }

################################################################################
#
# Rules we don't want to enable
#
################################################################################

Bundler/GemComment: { Enabled: false }
Lint/ConstantResolution: { Enabled: false }
Rails/RedundantPresenceValidationOnBelongsTo: { Enabled: false }
Rails/SchemaComment: { Enabled: false }
RSpec/AlignLeftLetBrace: { Enabled: false }
RSpec/AlignRightLetBrace: { Enabled: false }
Style/ConstantVisibility: { Enabled: false }
Style/Copyright: { Enabled: false }
Style/Documentation: { Enabled: false }
Style/DocumentationMethod: { Enabled: false }
Style/InlineComment: { Enabled: false }
Style/MissingElse: { Enabled: false }
Style/RequireOrder: { Enabled: false }
Style/SafeNavigation: { Enabled: false }
Style/StringHashKeys: { Enabled: false }
